"use client";
import React from "react";
import Link from "next/link";

export default function MainFooter() {
    return (
        <footer className="w-full py-8 mt-auto bg-white border-t border-slate-100 relative z-[5]">
            <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4 text-center md:text-left">
                <div className="space-y-1">
                    <p className="text-xs text-slate-400 font-bold tracking-wider uppercase">
                        Non-Profit Organization
                    </p>
                    <p className="text-sm text-slate-500">
                        © {new Date().getFullYear()} Moesekai. Generated by <span className="font-bold">Moesekai Dev Team</span>.
                    </p>
                    <div className="flex items-center justify-center md:justify-start gap-3 text-xs text-slate-400 pt-1">
                        <Link href="/privacy" className="hover:text-miku transition-colors">
                            隐私政策
                        </Link>
                        <span className="text-slate-200">·</span>
                        <Link href="/terms" className="hover:text-miku transition-colors">
                            服务条款
                        </Link>
                    </div>
                </div>

                <div className="text-xs text-slate-400 max-w-md leading-relaxed">
                    <p>
                        本站仅提供素材展示，游戏版权归 <span className="font-bold">SEGA / Colorful Palette</span> 所有。
                    </p>
                    <p>
                        这是一个粉丝向的网站，一个仅用于研究目的的同人数据库。
                    </p>
                </div>
            </div>
        </footer>
    );
}
